services:
  db:
    image: postgres:15
#    mem_limit: 300m
    container_name: education_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build: ./backend
#    mem_limit: 400m
    working_dir: /app/src
    command: >
      gunicorn core.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --threads 2
      --timeout 30
      --access-logfile -
      --error-logfile -
    container_name: education_backend
    restart: always
    volumes:
      - ./backend/src:/app/src
      - ./backend/static:/app/static
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: