"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import sys

import environ
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

CSRF_TRUSTED_ORIGINS = ['https://methodical-space.ru']

# Допустимые названия домена
ALLOWED_HOSTS = ['methodical-space.ru']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://methodical-space.ru",
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.


INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',  # Для авторизации Android
    'django_filters',
    'core',

    'drf_spectacular',

    'users',
    'library',
    'route',
    'main',
    'reflection'

]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [  # Аутентификация
        'rest_framework.authentication.TokenAuthentication',  # Для Android
        'rest_framework.authentication.SessionAuthentication',  # Для Web'а
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RequestLoggingMiddleware'
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': env.db(),
}

# TODO добавить bcrypt

# гуглить PwnedPasswordValidator
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Kaliningrad'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = '/var/www/backend/static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = '/var/www/backend/media/'

SPECTACULAR_SETTINGS = {
    'APPEND_COMPONENTS': {
        "securitySchemes": {
            "tokenAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Введите: Token <ваш_токен>"
            }
        }
    },
}

LOG_DIR = os.path.join(BASE_DIR, "request_logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'request_formatter': {
            'format': '{asctime} - {user} - {ip} - {path} - {status}',
            'style': '{',
        },
    },
    'handlers': {
        'daily_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'requests.log'),
            'when': 'midnight',  # новый файл каждый день
            'backupCount': 90,  # хранить 90 старых файлов
            'formatter': 'request_formatter',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'request_logger': {
            'handlers': ['daily_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}