limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    server_name methodical-space.ru;

    root /var/www/react;
    index index.html;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer;

    location / {
        try_files $uri /index.html;
    }

    location /assets/ {
        alias /var/www/react/assets/;
    }

    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;

        client_max_body_size 15M;

        proxy_pass http://education_backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 60s;
    }

    location /admin/ {
        proxy_pass http://education_backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/backend/static/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /var/www/backend/media/;
        access_log off;
        expires 7d;
    }

    location ~ /\.(env|git|svn|htaccess) {
        deny all;
        return 403;
    }

    location ~* (config|settings|secrets)\.(json|yml|yaml|toml|ini|py)$ {
        deny all;
        return 403;
    }

    if ($request_uri ~ "\.\.") {
        return 403;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/methodical-space.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/methodical-space.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = methodical-space.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name methodical-space.ru;
    return 404; # managed by Certbot
}
